### ISSUE TITLE
Can not download KEGGBackEnd

### ISSUE THREAD

**Issue by wang-zhengfeng** [CJ-Chen/TBtools#19]
Dear Dr. Chen,
我用KEGG enrichment时，不能下载keggbackend，怎么办呢？多谢多谢。报错如下：

[Debug...All Standard Error Info will show as following:...]
Curr log file:C:\Users\PC\AppData\Local\Temp\TBtools.17205861847920737976.20210330095119.log
Curr java version:11.0.4
Curr TBtools version:1.089
Maxmum Memory for Curr TBtools: 17163091968
curVersion:1.089:force
https://www.kegg.jp/kegg-bin/download_htext?htext=ath00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=aly00001.keg&format=htext&filedir=
statusCode:200
https://www.kegg.jp/kegg-bin/download_htext?htext=crb00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=csat00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=eus00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=brp00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=bna00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=boe00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=rsz00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=thj00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=cpap00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=cit00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=cic00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=tcc00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=gra00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=ghi00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=gab00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=dzi00001.keg&format=htext&filedir=
https://www.kegg.jp/kegg-bin/download_htext?htext=egr00001.keg&format=htext&filedir=
3月 30, 2021 9:53:46 上午 biocjava.GUIexcutors.KeggAnalysis.KeggEnrichmentGUI$5$1 run
严重: null
javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1315)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at toolsKit.HttpSgetData.getContent(HttpSgetData.java:71)
	at toolsKit.HttpSgetData.downloadFile(HttpSgetData.java:88)
	at biocjava.bioDoer.Kegg.AdvancedForEnrichment.UpdateKeggMap.prepareKegMap(UpdateKeggMap.java:270)
	at biocjava.GUIexcutors.KeggAnalysis.KeggEnrichmentGUI$5$1.run(KeggEnrichmentGUI.java:240)
	Suppressed: java.net.SocketException: Connection reset by peer: socket write error
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:351)
		... 17 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	... 13 more

非常感谢
王峥峰
2021.3.30

**Comment by CJ-Chen** [comment]
网络问题，直接去用户交流群 群文件 下载即可。
