### ISSUE TITLE
error in running basic biosequence view

### ISSUE THREAD

**Issue by labajay** [CJ-Chen/TBtools#49]
the error is as following
SEVERE: null
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at biocjava.bioDoer.MEME.DrawMotifPattern.DrawSequenceFromSeqLenInfo.metaParser(DrawSequenceFromSeqLenInfo.java:35)
	at biocjava.bioDoer.MEME.DrawMotifPattern.DrawMotifPatternFromMEMEResult.postGraph(DrawMotifPatternFromMEMEResult.java:1051)
	at biocjava.GUIexcutors.JJplot2LittleToolkit.SimpleBioSequnceViewerGUIPanel$4$1.run(SimpleBioSequnceViewerGUIPanel.java:332)

**Comment by CJ-Chen** [comment]
Please make sure the input file are tab-delimited. (Not Space-Delimited)
