### ISSUE TITLE
ASK for Professional help 

### ISSUE THREAD

**Issue by Buu89** [CJ-Chen/TBtools#50]
An error that I can't solve. Thank you so much!

[Debug...All Standard Error Info will show as following:...]
Curr log file:C:\Users\Lenovo\AppData\Local\Temp\TBtools.2006685913240871872.20230714162939.log
Curr java version:21
Curr TBtools version:1.130
Maxmum Memory for Curr TBtools: 4238344192
curVersion:1.120:force
Fetch Location:200
inline:## TBtools:Please update to the lastest version (higher than v1.09876). | https://tbtools.cowtransfer.com/s/be6d8daa56df4c
curS:Please update to the lastest version (higher than v1.09876). | https://tbtools.cowtransfer.com/s/be6d8daa56df4c
Factor(>0.6):0.0479726000536026
2023-07-14 16:30:10:Start Showing...
2023-07-14 16:30:10:Parsing Group Annotation...
2023-07-14 16:30:10:Fixing Duplicated Names...
7月 14, 2023 4:30:10 下午 biocjava.GUIexcutors.JIGplotToolkit.AmazingHeatMapGUIPanel$6$1 run
严重: null
java.lang.NumberFormatException: For input string: "Ctsd"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:792)
	at biocjava.bioDoer.JIGplotToolkit.HeatMap.heatmap2.fixedDuplicatedId(heatmap2.java:1150)
	at biocjava.bioDoer.JIGplotToolkit.HeatMap.heatmap2.show(heatmap2.java:1346)
	at biocjava.bioDoer.JIGplotToolkit.HeatMap.HeatmapControl2.showMeTheHeatMap(HeatmapControl2.java:357)
	at biocjava.GUIexcutors.JIGplotToolkit.AmazingHeatMapGUIPanel$6$1.run(AmazingHeatMapGUIPanel.java:271)

[[cmd.exe, /c, explorer /select, C:\Users\Lenovo\AppData\Local\Temp\TBtools.2006685913240871872.20230714162939.log]]
2023-07-14 16:31:45:Start Showing...
2023-07-14 16:31:45:Parsing Group Annotation...
2023-07-14 16:31:45:Fixing Duplicated Names...
7月 14, 2023 4:31:45 下午 biocjava.GUIexcutors.JIGplotToolkit.AmazingHeatMapGUIPanel$6$1 run
严重: null
java.lang.NumberFormatException: For input string: "Ctsd"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:792)
	at biocjava.bioDoer.JIGplotToolkit.HeatMap.heatmap2.fixedDuplicatedId(heatmap2.java:1150)
	at biocjava.bioDoer.JIGplotToolkit.HeatMap.heatmap2.show(heatmap2.java:1346)
	at biocjava.bioDoer.JIGplotToolkit.HeatMap.HeatmapControl2.showMeTheHeatMap(HeatmapControl2.java:357)
	at biocjava.GUIexcutors.JIGplotToolkit.AmazingHeatMapGUIPanel$6$1.run(AmazingHeatMapGUIPanel.java:271)

2023-07-14 16:36:41:Start Showing...
2023-07-14 16:36:41:Parsing Group Annotation...
2023-07-14 16:36:41:Fixing Duplicated Names...
7月 14, 2023 4:36:41 下午 biocjava.GUIexcutors.JIGplotToolkit.AmazingHeatMapGUIPanel$6$1 run
严重: null
java.lang.NumberFormatException: For input string: "Ctsd"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:792)
	at biocjava.bioDoer.JIGplotToolkit.HeatMap.heatmap2.fixedDuplicatedId(heatmap2.java:1150)
	at biocjava.bioDoer.JIGplotToolkit.HeatMap.heatmap2.show(heatmap2.java:1346)
	at biocjava.bioDoer.JIGplotToolkit.HeatMap.HeatmapControl2.showMeTheHeatMap(HeatmapControl2.java:357)
	at biocjava.GUIexcutors.JIGplotToolkit.AmazingHeatMapGUIPanel$6$1.run(AmazingHeatMapGUIPanel.java:271)

**Comment by CJ-Chen** [comment]
Input file format problem. check the turtorials at https://space.bilibili.com/541466667/channel/collectiondetail?sid=1167816
